node('build-slave') {
    try {
        String ANSI_GREEN  = "\u001B[32m"
        String ANSI_NORMAL = "\u001B[0m"
        String ANSI_BOLD   = "\u001B[1m"
        String ANSI_RED    = "\u001B[31m"
        String ANSI_YELLOW = "\u001B[33m"

        ansiColor('xterm') {

            stage('Checkout') {
                cleanWs()
                checkout scm
                commit_hash = sh(
                    script: 'git rev-parse --short HEAD',
                    returnStdout: true
                ).trim()

                artifact_version = sh(
                    script: "echo " + params.github_release_tag.split('/')[-1] + "_" + commit_hash + "_" + env.BUILD_NUMBER,
                    returnStdout: true
                ).trim()

                echo "artifact_version: ${artifact_version}"
            }

            stage('Build') {
                withEnv(["JAVA_HOME=${JAVA17_HOME}"]) {
                    sh """
                        echo "Using JAVA_HOME=\$JAVA_HOME"
                        java -version
                        mvn -version

                        mkdir -p sunbird_auth_24.0v
                        wget -q https://github.com/keycloak/keycloak/releases/download/24.0.4/keycloak-24.0.4.tar.gz
                        tar -xvf keycloak-24.0.4.tar.gz --strip 1 -C sunbird_auth_24.0v

                        mkdir -p sunbird_auth_24.0v/providers
                        mkdir -p sunbird_auth_24.0v/themes/sunbird/login

                        cd keycloak/sms-provider
                        mvn package -DskipTests

                        cp target/keycloak-email-phone-autthenticator-1.0-SNAPSHOT.jar \
                           \$WORKSPACE/sunbird_auth_24.0v/providers
                    """
                }
            }

stage('ArchiveArtifacts') {
    sh """
        mkdir -p keycloak_artifacts
        zip -r keycloak_artifacts.zip:${artifact_version} sunbird_auth_24.0v
    """

    archiveArtifacts artifacts: "keycloak_artifacts.zip:${artifact_version}",
                     fingerprint: true,
                     onlyIfSuccessful: true

    sh """
        cat <<EOF > metadata.json
{
  "artifact_name": "keycloak_artifacts.zip",
  "artifact_version": "${artifact_version}",
  "node_name": "${env.NODE_NAME}"
}
EOF
    """

    archiveArtifacts "metadata.json"
    currentBuild.description = "${artifact_version}"
}

        }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }
}
